// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBstGeXmdjBW5dAM9UhPS2atVY0UuIU6dI',
    appId: '1:509458332950:web:b646d9d63ebaa7cfa22437',
    messagingSenderId: '509458332950',
    projectId: 'skillup-da594',
    authDomain: 'skillup-da594.firebaseapp.com',
    storageBucket: 'skillup-da594.firebasestorage.app',
    measurementId: 'G-B7L0YYWECK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSGbi_Alq0xLl22d9CwwPD3ju5vqW6L-Q',
    appId: '1:509458332950:android:6f90adb8453e2481a22437',
    messagingSenderId: '509458332950',
    projectId: 'skillup-da594',
    storageBucket: 'skillup-da594.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe8HzENYA3CrLP0QBNrV1pNjZwphR1FP4',
    appId: '1:509458332950:ios:068d28baf5309428a22437',
    messagingSenderId: '509458332950',
    projectId: 'skillup-da594',
    storageBucket: 'skillup-da594.firebasestorage.app',
    iosBundleId: 'com.app.skillUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe8HzENYA3CrLP0QBNrV1pNjZwphR1FP4',
    appId: '1:509458332950:ios:ba7c7950f6374633a22437',
    messagingSenderId: '509458332950',
    projectId: 'skillup-da594',
    storageBucket: 'skillup-da594.firebasestorage.app',
    iosBundleId: 'com.example.skillUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBstGeXmdjBW5dAM9UhPS2atVY0UuIU6dI',
    appId: '1:509458332950:web:e9f0ad8cb41556dea22437',
    messagingSenderId: '509458332950',
    projectId: 'skillup-da594',
    authDomain: 'skillup-da594.firebaseapp.com',
    storageBucket: 'skillup-da594.firebasestorage.app',
    measurementId: 'G-DSEFWG1NNZ',
  );
}
